# docker-compose.yml
version: '3'

services:
  leave-mcp-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DEBUG_MODE=False
      - SERVER_NAME=LeaveManagement
